#ifndef __ADTDEFS_H__
#define __ADTDEFS_H__
typedef enum{
	ERR_OK = 0,
	TRUE,
	FALSE,
	ERR_NOT_INITIALIZED,
	ERR_ALOCATION_FAILED,
	ERR_UNDERFLOW,
	ERR_STRUCT_EMPTY,
	ERR_DUPLICATE_INSERT,
	ERR_WRONG_INDEX,
	ERR_OVERFLOW,
	ERR_REALOOCATION_FAILED
}ADTErr;

typedef enum
{
PRE_ORDER,
IN_ORDER,
POST_ORDER
} TreeTraverse;
#endif /*__ADTDEFS_H__*/
